#!/bin/bash

# Asteroids Game Heroku Deployment Script
echo "Deploying Asteroids Game to Heroku..."
echo "====================================="

# Check if Heroku CLI is installed
if ! command -v heroku &> /dev/null; then
    echo "❌ Heroku CLI is not installed. Please install it and try again."
    echo "   Installation instructions: https://devcenter.heroku.com/articles/heroku-cli"
    exit 1
fi

# Check if user is logged in to Heroku
heroku whoami &> /dev/null
if [ $? -ne 0 ]; then
    echo "You need to log in to Heroku first."
    heroku login
fi

# Ask for app name
echo -e "\nEnter a name for your Heroku app (letters, numbers, and dashes only):"
read app_name

if [ -z "$app_name" ]; then
    echo "Using a random app name generated by Heroku."
    # Create Heroku app with random name
    heroku create
else
    # Create Heroku app with specified name
    heroku create $app_name
fi

# Set environment variables
echo -e "\nSetting environment variables..."
heroku config:set NODE_ENV=production

# Deploy to Heroku
echo -e "\nDeploying to Heroku..."
git add .
git commit -m "Prepare for Heroku deployment" --allow-empty
git push heroku main

# Open the app in browser
echo -e "\nOpening app in browser..."
heroku open

echo -e "\n====================================="
echo "✅ Deployment completed!"
echo "Your Asteroids game is now live at:"
heroku apps:info | grep "Web URL" | cut -d: -f2- | xargs
echo "=====================================" 